name: Create GitHub release for tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: write
  packages: write
  checks: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up JDK 21
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew stage
      - name: Archive production artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release
          path: build/libs/diabot.jar

      - name: Setup QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069
        with:
          version: v0.27.0

      - name: Build and push Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          # This will use a dockerfile which copies the already-built JAR from `build/libs/`
          file: nobuild.Dockerfile
          context: .
          push: true
          platforms: "linux/arm64,linux/amd64,linux/arm64/v8"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        if: github.ref_type == 'tag'
        with:
          files: build/libs/diabot.jar
          generate_release_notes: true
          draft: true
